SELECT  loyalty
      , refunds
      , payments
      , items
      , tipStatus
      , original_subtotal
      , customer
      , attributes
      , syncStatus
      , status
      , employee_name
      , isTaxExempt
      , device_token
      , total
      , offline_mode
      , mode
      , server_time
      , date_completed
      , order_date
      , device_order_time
      , venue_id
      , employee_id
      , ext_vendor_id
      , order_type
      , vendor_name
      , vendor_id
      , reductions
      , order_mode
      , employee
      , device_type
      , feeExtended
      , card_type
      , customFees
      , timezone
      , courseCode
      , promo
      , venue_name
      , promo_code
      , reasons
      , user_seat_id
      , discounts_applied
      , guestCount
      , device_name
      , create_time
      , fee
      , discount
      , vendorCloseTime
      , tax
      , eventId
      , deviceOrderId
      , vendorOpenTime
      , tip
      , payment_type
      , order_source
      , date_modified
      , order_id

FROM    {{ source('rotio_lab', 'appetize_test') }}